### ISSUE TITLE
Naming change: Authenticate -> Authentication (or just Auth)?

### ISSUE THREAD

**Issue by rafalp** [florimondmanca/starlette-auth-toolkit#17]
Super cool project BTW, I very much like what I see!

Only think that came as odd to me: I would like to propose changing naming from `Authenticate` to `Authentication` (or cutting to just `Auth`), which I believe is more natural English:

```
TokenAuthenticate -> TokenAuthentication -> TokenAuth
DBAuthenticate -> DBAuthentication -> DBAuth
ModelAuthenticate -> ModelAuthentication -> ModelAuth
FacebookAuthenticate -> FacebookAuthentication -> FacebookAuth
```

**Comment by florimondmanca** [comment]
> Super cool project BTW, I very much like what I see!

Thanks!

About naming: actually, authentication backends are named XAuthBackend, eg BasicAuthBackend. I thought about using XAuthentication/XAuth, but since they are abstract classes the name would conflict with the necessary subclass we’d make. Maybe BaseXAuth would be nicer?

There’s BaseAuthenticate but the naming idea behind it was that it would allow to build authentication helper functions, hence a verb-oriented naming. I agree it’s not the most natural thing when I look at it again, though! Maybe a very explicit BaseAuthenticationHelper would come across as less odd?

**Comment by florimondmanca** [comment]
By the way, I think I’ll also rename BearerAuth to TokenAuth, because Bearer is a complete OAuth2 standard but the current implementation is much simpler (very akin to DRF’s TokenAuthentication).
